name: 'Column Issue Label Remover'
description: 'For each column in a list, labels are removed from all its issues.'
inputs:
  columns_labels:
    description: 'An array of objects each containing a column reference and an array of labels to add'
    required: true
  token:
    description: 'github token'
    required: true
    default: ''
runs:
  using: 'node12'
  main: 'index.js'
